Use transient artifactory location for non-release uploads
If the parameter to upload artifacts to artifactory is checked when
building, the upload happens currently to MAAXA folder that retains
artifacts forever. Instead, for builds from branches other than release
branches, push to transient MAAXA-SNAPSHOT folder as is done by other
projects. This also prevents somebody accidentally uploading artifacts
from a PR build and overwriting a release build's artifacts, as the
location is based on the version set in gradle.properties.

- Create a new common file shared between build and deploy Jenkinsfiles
  that has functions to get application version, and to get upload path
  in artifactory, based on the branch name.
- Use `MAAXA/builds/uaa/<version>/` folder as before for build/deploy of
  release_xxxx branches
- Use `MAAXA-SNAPSHOT/builds/uaa/<branch-name>` for build/deploy of
  non-release branches

With this change, it is possible to trigger a branch build job (branch
or PR) with the parameter to upload artifacts enabled, and then trigger
a branch deploy job which will automatically pick the artifact uploaded
by the corresponding branch build job (based on branch/PR name).

diff --git a/DeployJenkinsfile b/DeployJenkinsfile
--- a/DeployJenkinsfile
+++ b/DeployJenkinsfile
@@ -38,22 +38,27 @@ pipeline {
                     checkout scm
                 }
                 script {
-                    APP_VERSION = sh (returnStdout: true, script: '''
-                        grep 'version' uaa/gradle.properties | sed 's/version=//'
-                        ''').trim()
-                    echo "Downloading UAA  ${APP_VERSION} Artifact Artifactory"
+                    def util = load('uaa/JenkinsfileCommon.groovy')
+                    ARTIFACTORY_PATH = util.getArtifactoryPath()
+                    WAR_FILE_NAME = util.getWarFileName()
                     def downloadSpec = """{
                         "files": [
                             {
                                 "target": "deploy-workspace/",
                                 "flat": "true",
-                                "pattern": "MAAXA/builds/uaa/${APP_VERSION}/*.war"
+                                "pattern": "${ARTIFACTORY_PATH}/*.war"
                             }
                         ]
                     }"""
-                    sh 'pwd && ls -ltr'
+
+                    echo "Downloading ${WAR_FILE_NAME} from ${ARTIFACTORY_PATH}"
                     buildGeArtServer.download(downloadSpec)
-                    sh "ls -ltr deploy-workspace/"
+                    // NOTE: ci-deploy.sh depends on deploy-workspace/${WAR_FILE_NAME} location and file name format
+                    // So make sure it is what got downloaded.
+                    sh """
+                        ls -l "deploy-workspace/${WAR_FILE_NAME}" || \
+                          (echo "${WAR_FILE_NAME} not found!" && ls -l deploy-workspace && exit 1)
+                       """
                 }
 
                 dir('deploy-workspace') {
@@ -133,7 +138,8 @@ pipeline {
                 }
 
                 script {
-                    echo "Publishing UAA ${APP_VERSION} Artifact to Artifactory" 
+                    APP_VERSION = util.getAppVersion()
+                    echo "Publishing UAA ${APP_VERSION} Artifact to Artifactory"
                     def uploadSpec = """{
                         "files": [
                             {
