Dockerfile understands needed DB env vars
Signed-off-by: aram price <aprice@pivotal.io>
Co-authored-by: aram price <aprice@pivotal.io>

diff --git a/server/migrations/Dockerfile b/server/migrations/Dockerfile
--- a/server/migrations/Dockerfile
+++ b/server/migrations/Dockerfile
@@ -28,28 +28,26 @@ COPY UAA-FlywayMigrationRunner-0.0.0-all.jar UAA-FlywayMigrationRunner-0.0.0-all
 # is this better b/c it doesn't know about concourse? RUN install git fetch repo get gradle and build jar
 
 # MySQL
-#ENV DB_SCHEMA="mysql"
-#ENV DB_HOST=""
+#ENV DB_SCHEME="mysql"
 #ENV DB_USERNAME=""
 #ENV DB_PASSWORD=""
-#ENV DB_PORT="3306"
+#ENV DB_URL="jdbc:${DB_SCHEME}://${DB_HOST}:3306/uaa"
 
 # Postgres
-#ENV DB_SCHEMA="postgres"
-#ENV DB_HOST=""
+#ENV DB_SCHEME="postgres"
 #ENV DB_USERNAME=""
 #ENV DB_PASSWORD=""
-#ENV DB_PORT="5432"
+#ENV DB_URL="jdbc:${DB_SCHEME}://${DB_HOST}:5432/uaa"
 
 ENV DB_SCRIPT="/migrate.sh"
-RUN echo "#!/usr/bin/env bash"                                                  >> "${DB_SCRIPT}" \
-    && echo "set -eu -o pipefail"                                               >> "${DB_SCRIPT}" \
-    && echo "java \\"                                                           >> "${DB_SCRIPT}" \
-    && echo "-Dspring.profiles.active=${DB_SCHEMA} \\"                          >> "${DB_SCRIPT}" \
-    && echo "-Ddatabase.username=${DB_USERNAME} \\"                            >> "${DB_SCRIPT}" \
-    && echo "-Ddatabase.password=${DB_PASSWORD} \\"                            >> "${DB_SCRIPT}" \
-    && echo "-Ddatabase.url='jdbc:${DB_SCHEMA}://${DB_HOST}:${DB_PORT}/uaa' \\" >> "${DB_SCRIPT}" \
-    && echo "-jar UAA-FlywayMigrationRunner-0.0.0-all.jar"                      >> "${DB_SCRIPT}" \
+RUN echo "#!/usr/bin/env bash"                             >> "${DB_SCRIPT}" \
+    && echo "set -eu -o pipefail"                          >> "${DB_SCRIPT}" \
+    && echo "java \\"                                      >> "${DB_SCRIPT}" \
+    && echo '-Dspring.profiles.active=${DB_SCHEME} \\'     >> "${DB_SCRIPT}" \
+    && echo '-Ddatabase.username=${DB_USERNAME} \\'        >> "${DB_SCRIPT}" \
+    && echo '-Ddatabase.password=${DB_PASSWORD} \\'        >> "${DB_SCRIPT}" \
+    && echo '-Ddatabase.url='${DB_URL}' \\'                >> "${DB_SCRIPT}" \
+    && echo '-jar UAA-FlywayMigrationRunner-0.0.0-all.jar' >> "${DB_SCRIPT}" \
     && chmod 755 "${DB_SCRIPT}"
 
 CMD ${DB_SCRIPT}
